### ISSUE TITLE
Extend the coverage of external identifiers extraction from JATS references

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1128]
Originally requested on redmine: [#4208#note-3](https://issue.openaire.research-infrastructures.eu/issues/4208#note-3).

Currently we extract external identifiers out of the JATS reference section only when explicitly tagged with `pub-id` element  e.g.:

```
<pub-id pub-id-type="pmid">10056053</pub-id>
```

while there are also less explicitly defined identifiers such as:

```
<ext-link ext-link-type="uri" xlink:href="http://dx.doi.org/10.1016/S0921-4526(99)01270-3">doi:10.1016/S0921-4526(99)01270-3</ext-link>
```
we should reach for those identifiers as well in order to extend the potential matching coverage. This was the original issue reported in redmine [#4208](https://issue.openaire.research-infrastructures.eu/issues/4208).

We could also scan through the references within JATS records to identify other cases of non-explicit external identifiers definition.

**Comment by przemyslawjacewicz** [comment]
After scanning through references within JATS records it turns out that we can gain the most after addition of handling of other citation elements from JATS references, especially citations given using `element-citation` tag. The full results of the analysis are given in #1196 .

This issue will remain open for any further work involving external identifiers in `ext-link` elements.

**Comment by przemyslawjacewicz** [comment]
Following sprint planning conclusions I'm closing this ticket - we're not going to add `ext-link` elements now.
