### ISSUE TITLE
Fix multibranch build failing when more than one build is being run in parallel

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1134]
I just noticed the multibranch build for a newly created branch `marekhorst_1132_fix_http_connection_pool_handling` has failed:

http://ci.ceon.pl/job/iis_build_multibranch/job/marekhorst_1132_fix_http_connection_pool_handling/2/

with the following unit test error:

```
Path does not exist: file:/srv/yadda-jenkins/app/workspace/tp_connection_pool_handling-7BTP7MM64PLLYOZDVA67NVVWYNKYYC65ZRPJFHBI7E5YN4CASU6A%402/iis-wf/iis-wf-import/target/test-classes/eu/dnetlib/iis/wf/importer/patent/sampletest/oozie_app/input/patents_epo.tsv;
```

I've seen similar errors before but just did care too much, I thought those are some problems of an intermittent kind.

It looks like the path contains the `%402` character which might be the cause of the problem (the test run locally succeeds).

When I looked at the set of all the jobs being run for the branch:
http://ci.ceon.pl/job/iis_build_multibranch/job/marekhorst_1132_fix_http_connection_pool_handling/
I found two of them, triggered almost at the same time. I guess the first one was triggered after the branch was pushed to the origin repository while the second when issuing a pull request. @przemyslawjacewicz, could it be the case?

Anyway, if the two executions were expected then we are left with one issue to be solved only:)

I have found one resource describing very similar issue:
https://stackoverflow.com/questions/39553523/jenkins-failures-due-to-an-extra-402-character-in-the-location-address
which might be helpful in solving our problem.

**Comment by marekhorst** [comment]
This is something I have read before in the context of putting `.m2` repository in a working directory: if there are at least two builds run in parallel then the path is supplemented with `@n` where the `n` is the build number.

**Comment by przemyslawjacewicz** [comment]
The source of this problem is the way file paths are retrieved during tests from test resource dirs. When using `classloader -> resource -> file` pipeline the string that is returned is UTF-8 encoded, so every special character will be represented as it's code. Check this StackOverflow thread with similar problem: [Java ClassLoader getResource with special characters in path](https://stackoverflow.com/questions/32251251/java-classloader-getresource-with-special-characters-in-path) .

The solution is to decode the path using `URLDecoder.decode` method.

**Comment by przemyslawjacewicz** [comment]
As discussed in PR #1147 we decided to introduce a common functionality for handling resources and to apply it for resource related IIS code. The related issue is #1151 .
