### ISSUE TITLE
Do not persist transient errors in caches

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1136]
Currently all exceptions occurring during patent metadata retriever communication with remote EPO endpoint, which are being handled by `PatentMetadataRetrieverJob#getMetadataFromFacade()`, are persisted within the cache alongside an empty patent content. Similarly in `CachedWebCrawlerJob`, responsible for web pages retrieval, any error is stored within the cache.

This is an expected behaviour for persistent errors but not for transient ones. Those temporary errors may occur e.g. when remote EPO (or software repository) endpoint rate limits the client quite severely resulting in exceeding the retries limit (set to 20 by default with 10 secs wait interval between the retries).

We should distinguish one type of errors from the other and whenever an exception is a result of temporary problems we should return the appropriate fault and empty patent metadata contents, as we do it right now, but we **should not** persist this pair within the cache. It should be possible to retry the patent retrieval in the next IIS round.

**Comment by marekhorst** [comment]
We could handle this case by introducing e.g. `ContentRetrieverResponse#permanentlyUnavailable` flag which could be set to `false` only in some special cases such as rate-limiting etc.

This way when handling this flag within job logic we could filter-out the responses bound to temporary resource unavailability and prevent them (both empty records and `Fault`s) from being stored in cache.

The same logic should be applied to:
* patent metadata retrieval (`PatentMetadataRetrieverJob`)
* software pages web crawler (`CachedWebCrawlerJob`)

Set of unit tests should be supplemented with appropriate test cases.

**Comment by przemyslawjacewicz** [comment]
## Patent metadata retrieval execution

I've run `PatentMetadataRetrieverJob` with PROD input data and empty cache
* total number of retrieved patent metadata: 3887
* total number of faults: 34
* all faults are the same:
```text
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
```

In `HttpClientUtils` we create `CloseableHttpClient` and use the same value for connect timeout and connection request timeout. The second timeout value determines how long to wait when requesting a connection from connection manager and exceeding this value results in `org.apache.http.conn.ConnectionPoolTimeoutException`. It seems we could increase/disable this timeout and bring the number of faults down. Creating a ticket.

**Comment by przemyslawjacewicz** [comment]
## HTTP content retrieval job

I've run `CachedWebCrawlerJob` with PROD input data and empty cache and the job is running now for almost 30hrs and only `text` cache was written. Currently faults are being written to `fault` cache. Unfortunately the logs show that the job is retrieving http content again! This means that the we're missing some caching in the job. I'm creating a dedicated issue to fix this. I'm going to terminate the job because the job will take another 30hrs just create `fault` cache and probably even more for output. As for checking the type of unhandled exceptions/errors - it is not possible without `fault` written to cache or output because we're not logging the responses. The only thing I can do is check the logs for any exceptions thrown and group by their type.

**Comment by przemyslawjacewicz** [comment]
Running the unchanged `CachedWebCrawlerJob` (that is from current master branch) with a single site to read shows that we're retrieving content from external service three times. So this problem is not due to the changes this issue does but is more generic. I'm creating a ticket to fix this.

**Comment by przemyslawjacewicz** [comment]
Simple analysis of logs from cached webcrawl job
```shell
[przemyslaw.jacewicz@iis-cdh5-test-gw ~]$ grep "starting content" application_1603828052984_39740.log | wc -l
163181
[przemyslaw.jacewicz@iis-cdh5-test-gw ~]$ grep "Exception" application_1603828052984_39740.log | wc -l
6481
```
Grouping by exception type:
```shell
org.apache.http.conn.ConnectionPoolTimeoutException -> 4594
java.net.UnknownHostException -> 846
java.lang.IllegalArgumentException -> 454
java.net.URISyntaxException -> 454
java.net.SocketTimeoutException -> 60
org.apache.http.client.ClientProtocolException -> 19
org.apache.http.client.CircularRedirectException -> 11
sun.security.provider.certpath.SunCertPathBuilderException -> 6
https://github.com/TypecastException -> 5
http://code.google.com/p/solidbase/wiki/Exception -> 4
https://github.com/AnesBendimerad/ClosedException -> 4
javax.net.ssl.SSLException -> 4
sun.security.ssl.Alerts.getSSLException -> 4
java.io.FileNotFoundException -> 3
https://github.com/AnesBendimerad/Exception -> 2
org.apache.http.NoHttpResponseException -> 2
org.apache.http.ProtocolException -> 2
javax.net.ssl.SSLHandshakeException -> 1
org.apache.spark.SparkException -> 1
org.apache.spark.util.Utils$.logUncaughtException -> 1
```
So only a few exceptions are thrown while retrieving content: only 6481 out of 163181 cases. Majority of exceptions are due to  `org.apache.http.conn.ConnectionPoolTimeoutException`.

This simple analysis takes into account exceptions thrown but it does not count valid but unhandled responses from http servers, which are not logged. Those responses are wrapped into failures and are persisted into cache and output. But the job was killed before those datastores were written out.
