### ISSUE TITLE
Citation matching stage occupies resources for a very long time 

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1159]
I just noticed the citation matching algorithm occupies most of the cluster resources (capped at 80% of total resources by scheduler but still) during one of its stages:

http://iis-cdh5-test-m1.ocean.icm.edu.pl:8088/proxy/application_1595483222400_14384/stages/stage?id=21&attempt=0

namely `mapPartitionsToPair at BestMatchedCitationPicker.java:42` which lasts for over 4h (and counting). This makes it very difficult to recollect resources for other jobs including analytics.

We should take a closer look at the calculations being made and optimize it. One of the approaches could be increasing the number of partitions (currently set to 1000) for this stage to get more tasks running this job (thus decreasing the amount of time each stage lasts).

We should also take a closer look at other mining modules and search for similar cases. Most of them were already eliminated by #991.

**Comment by marekhorst** [comment]
Last time fuzzy citation matching took over 7.5h in total on PROD (8.5h on BETA) so we should also take a look at potential performance optimization of this algorithm (not only letting it run by more tasks).

**Comment by przemyslawjacewicz** [comment]
To reduce the execution time of the job we could try out some modifications within the job and try out increasing number of partitions. 

The stage with long execution time is deep within coansys part of the job. The job is configurable from IIS so we could test some changes that would prepare data for the stage and theoretically reduce the execution time. But the job is still in Spark 1.6.0 where the only interface for partitioning is based on custom partitioner. Writing a custom partitioner for the stage turned out to be quite challenging and did not bring any success.

Increasing the number of partitions turned out to be more successful. Initial value for the partitions was 1000 and I've run the job with 3300, 10000 and 20000. The durations of the longest stage were 4.8h, 4.3h and 4.6h respectively. Other workflows were run on the cluster at the time of execution of the jobs so the number are not entirely comparable I think that we could go with 10000 partitions with possible further increase to 20000 (or more).

**Comment by przemyslawjacewicz** [comment]
| number of partitions | link                                                                                                                              |
|----------------------|-----------------------------------------------------------------------------------------------------------------------------------|
| 3300                 | [application_1595483222400_18324](http://iis-cdh5-test-gw.ocean.icm.edu.pl:18088/history/application_1595483222400_18324/1/jobs/) |
| 10000                | [application_1595483222400_16904](http://iis-cdh5-test-gw.ocean.icm.edu.pl:18088/history/application_1595483222400_16904/1/jobs/) |
| 20000                | [application_1595483222400_18482](http://iis-cdh5-test-gw.ocean.icm.edu.pl:18088/history/application_1595483222400_18482/1/jobs/) |

**Comment by marekhorst** [comment]
Based on comparison of stage 21 executions for different number of partitions:
| number of partitions | link                                                                                                                              |
|----------------------|-----------------------------------------------------------------------------------------------------------------------------------|
| 1000                 | [application_1595483222400_14384#stage21](http://iis-cdh5-test-gw.ocean.icm.edu.pl:18088/history/application_1595483222400_14384/1/stages/stage/?id=21&attempt=0) |
| 10000                | [application_1595483222400_16904#stage21](http://iis-cdh5-test-gw.ocean.icm.edu.pl:18088/history/application_1595483222400_16904/1/stages/stage/?id=21&attempt=0) |

there are several facts worth noting:
* primary goal was achieved: task median execution time was reduced from `2.1 h` down to `13 min` so the resources should be returned back to the pool more frequently
* secondary goal seems to achieved: total stage 21 execution time was reduced from `6.5 h` down to `4.3 h` (not sure about the cluster utilization level because **Total Time Across All Tasks** was slightly increased `2140.9 h` up to `2246.5 h`)
* both memory and shuffle spills were almost eliminated
