### ISSUE TITLE
Perform JATS references analysis before extending the coverage of external identifiers extraction

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1196]
This is the preliminary task to be undertaken before #1128.

We need to analyze the bibliographic references in JATS records to see how many DOIs (and possibly other kinds of ids) are not explicitly tagged as `pub-id`s and which could potentially be retrievable using different, less-explicit techniques.

Hint: we could do the little short-cut and, instead of parsing full JATS XML records, start with picking up all the references (by processing the avro records holding `ReferenceMetadata` e.g. provided as citation matching input) having DOIs among the `ReferenceMetadata#text` fields but not having them explicitly recognized and stored as `ReferenceMetadata#basicMetadata#externalIds`.

**Comment by przemyslawjacewicz** [comment]
I've downloaded raw XML data for PROD and BETA using `primary_import` workflow and done basic analysis. I've looked for references and XML tags used to describe citations. Then I've looked for publication identifiers inside citations tags and checked which identifiers are present. I've done basic counts and aggregations concentrating on two most common identifiers: `pmid` and 'doi`. 

I've wanted to link Zeppelin note with code used and the results but Zeppelin turned out to be unstable at the time so I've moved to `spark-shell`. Unfortunately this means that I can't attach the code used for analysis and link to Spark history so I'm going to put the code to ICM's gitlab repo for any further usage.

**Comment by przemyslawjacewicz** [comment]
## PROD

### XML count

| env  | XML count | valid XML count |
|------|-----------|-----------------|
| PROD | 3414352   | 3413751         |

Note: there is a small number (601) of documents with malformed xml structure.

### XML root element name

| XML root tag name | count   |
|-------------------|---------|
| `article`         | 2934409 |
| `record`          | 479342  |

Note: `record` elements contain `article` elements inside `metadata` elements.

### Reference count

Total number of reference elements `ref`: 126857881.

| citation element tag name  | count    | share [%] |
|----------------------------|----------|---|
| `citation`                 | 3418115  | 2.7|
| `element-citation`         | 64602635 | 50.9|
| `mixed-citation`           | 53553334 | 42.2|
| `nlm-citation`             | 4788881  | 3.8 
| no element/invalid element | 494916   | 0.4 |

Note: there is a small number of articles without references (494916) but it's only about 0,4% of total number of references. 

### Identifiers in `pub-id` element

Citation element contains `pub-id` elements with different types of publication identifiers.

#### References with `citation` element

| pub-id-type  | count   |
|--------------|---------|
| doaj         | 1       |
| doi          | 1175223 |
| pmid         | 2353961 |
| publisher-id | 336     |

Number of references with PMID only: 1273304.
Number of references with DOI only: 95535.
Number of references with PMID and DOI: 1079682.

#### References with `element-citation` element

| pub-id-type   | count    |
|---------------|----------|
| accession     | 468      |
| archive       | 12       |
| art-access-id | 38       |
| arxiv         | 4851     |
| doaj          | 3        |
| doi           | 25082890 |
| isbn          | 52       |
| medline       | 259076   |
| other         | 3558756  |
| pii           | 8859     |
| pmcid         | 4105     |
| pmid          | 41890506 |
| publisher-id  | 131778   |

Number of references with PMID only: 22194611.
Number of references with DOI only: 5408312.
Number of references with PMID and DOI: 19662516.

#### References with `mixed-citation` element

| pub-id-type   | count    |
|---------------|----------|
| accession     | 15       |
| art-access-id | 27       |
| arxiv         | 13       |
| coden         | 9768     |
| doi           | 18698377 |
| isbn          | 13       |
| medline       | 40       |
| other         | 3889     |
| pii           | 18       |
| pmcid         | 370      |
| pmid          | 33110895 |
| publisher-id  | 354      |
| null          | 28       |

Number of references with PMID only: 16995105.
Number of references with DOI only: 2582497.
Number of references with PMID and DOI: 16077599.

#### References with `nlm-citation` element

| pub-id-type   | count   |
|---------------|---------|
| art-access-id | 12      |
| doaj          | 5       |
| doi           | 3179099 |
| other         | 3792466 |
| pii           | 1       |
| pmid          | 2384    |
| publisher-id  | 141409  |
| null          | 5       |

Number of references with PMID only: 2045.
Number of references with DOI only: 3178073.
Number of references with PMID and DOI: 339.

### Identifiers in `ext-link` element

#### References with `citation` element

|ext-link-type|  count|
|-------------|-------|
|         null|3348968|
|          ftp|     14|
|          uri|  69126|
|          url|      7|

#### References with `element-citation` element

|ext-link-type|   count|
|-------------|--------|
|         null|64438698|
|          doi|    9721|
|          ftp|       9|
|          uri|  153318|
|      webcite|     889|

#### References with `mixed-citation` element

|     ext-link-type|   count|
|------------------|--------|
|              null|51904126|
|ClinicalTrials.gov|       5|
| DDBJ/EMBL/GenBank|      17|
|          NCBI:geo|       3|
|               PDB|       1|
|               doi|   88894|
|               ftp|     824|
|               gen|       5|
|               pmc|       1|
|             pmcid|       4|
|              pmid|    1540|
|               uri| 1557914|

#### References with `nlm-citation` element

There is no `ext-link` element in references.

### Summary

Currently we only process references with `mixed-citation` and when only PMID and DOI are counted we process 51809272 (52M) publication identifiers. If we count references with other citation elements, that is `citation`, `element-citation` and `nlm-citation` and count only for PMID and DOI identifiers we get 73684063 (73M) additional identifiers. 

The number of identifiers inside `ext-link` element for all references is very small when compared to identifiers inside `pub-id` element.

**Comment by marekhorst** [comment]
I should probably find & provide this [#760](https://issue.openaire.research-infrastructures.eu/issues/760) link in the beginning but let's keep it connected with this one. It is pretty old although it is related to XML PMC subset analysis. Probably outdated as the XML set has grown significantly since then.

**Comment by przemyslawjacewicz** [comment]
It turns out that we already could be processing citations given as `citation`, `element-citation` and `mixed-citation` using `eu.dnetlib.iis.wf.ingest.pmc.metadata.RefListXmlHandler`. I'm going to compare the numbers and check if the numbers match.

**Comment by przemyslawjacewicz** [comment]
I have compared the numbers from last PROD run (2020-12-15) of IIS with my run of `primary_import` which downloaded raw XMLs for analysis (2020-12-01). The number do not match one-to-one but this is probably due to the different configuration of runs. The following table contains the comparison

|                       | IIS run   | IIS run [M] | analysis run | analysis run [M] |
|-----------------------|-----------|-------------|--------------|------------------|
| XML count             | 3552108   | 3.6         | 3414352      | 3.4              |
| total reference count | 139334375 | 139.3       | 126857881    | 126.9            |
| PMID references       | 82899737  | 82.9        | 77357746     | 77.4             |
| DOI references        | 52577696  | 52.6        | 48135589     | 48.1             |

So the numbers show that we are extracting the bulk of existing identifiers. Code analysis of `eu.dnetlib.iis.wf.ingest.pmc.metadata.RefListXmlHandler` shows that we do not extract identifiers from citations with `nlm-citation` tag.  In the analysis we have 3181483/3.2M references with this tag so we could slightly increase the number of extracted identifiers. I'm going to create a ticket to add extraction of citations with `nlm-citation` tag.

**Comment by marekhorst** [comment]
We could do one more check: how many of `ext-link` elements with undefined `ext-link-type` (set to `null` which is vast majority of cases) do include DOI, e.g. by simply checking if the element content starts with `doi:` prefix.

**Comment by przemyslawjacewicz** [comment]
> We could do one more check: how many of `ext-link` elements with undefined `ext-link-type` (set to `null` which is vast majority of cases) do include DOI, e.g. by simply checking if the element content starts with `doi:` prefix.

This table contains the results:

| citation element name | number of `ext-link` with DOI number | number of citation ref elements | share [%] |
|-----------------------|--------------------------------------|---------------------------------|-----------|
| `citation`            | 5959                                 | 3418115                         | 0.17      |
| `element-citation`    | 51132                                | 64602635                        | 0.08      |
| `mixed-citation`      | 314926                               | 53553334                        | 0.59      |
| `nlm-citation`        | 0                                    | 4788881                         | 0         |

**Comment by przemyslawjacewicz** [comment]
I've also checked the publication referred in redmine ticket

> https://beta.explore.openaire.eu/search/publication?articleId=dedup_wf_001::931e4616e5194c7d03ddd7c772437963

and its references. The XML reference not matched is described by this XML
```xml
			<ref id="RSPA20150711C3">
				<label>3</label>
				<mixed-citation publication-type="journal">
					<person-group person-group-type="author">
						<name>
							<surname>Aksenov</surname>
							<given-names>VL</given-names>
						</name>, 
						<name>
							<surname>Nikitenko</surname>
							<given-names>YV</given-names>
						</name>, 
						<name>
							<surname>Radu</surname>
							<given-names>F</given-names>
						</name>, 
						<name>
							<surname>Gledenov</surname>
							<given-names>YM</given-names>
						</name>, 
						<name>
							<surname>Sedyshev</surname>
							<given-names>PV</given-names>
						</name>
					</person-group>
					<year>2000</year>
					<article-title>Observation of resonance enhanced neutron standing waves through (
						<italic>n</italic>,
						<italic>&#x3B1;</italic>) reaction
					</article-title>. 
					<source>
						<italic>Physica B</italic>
					</source>
					<volume>276&#x2013;278</volume>, 
					<fpage>946</fpage>&#x2013;
					<lpage>947</lpage>. (
					<ext-link ext-link-type="uri" xlink:href="http://dx.doi.org/10.1016/S0921-4526(99)01270-3">doi:10.1016/S0921-4526(99)01270-3</ext-link>)
				</mixed-citation>
			</ref>
```
So `mixed-citation` element is used what means that current IIS parser should process this reference. But there is no `pub-id` element so just like described in the ticket we would have to add `ext-link` processing to match this reference.

**Comment by przemyslawjacewicz** [comment]
One more comparison to : 
* total number of references: 126857881
* total number of references without `pub-id` (so not processed by IIS): 104251582

So we do not process quite a lot of references (22.6M) because they do not contain the `pub-id` element. And adding support for `ext-link` does not help because only a handful of references contain DOI number in `ext-link` elements.
