### ISSUE TITLE
Integrate Bio Entities mining with IIS dedicated branch

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1215]
Originally requested on redmine:

https://issue.openaire.research-infrastructures.eu/issues/5291#note-79

This is in the scope of springer-driven experiments so the intention is to integrate it on a new springer dedicated branch including bio entities and already existing springer-related work:

https://github.com/openaire/iis/compare/marekhorst_1039_extract_plaintexts_from_NLM_records_provided_by_SN_as_zip_packages

and let it live there for a while.

**Comment by przemyslawjacewicz** [comment]
Working branch for this integration is `przemyslawjacewicz_1215_bio_entities_integration` - branched off fresh master with `marekhorst_1039_extract_plaintexts_from_NLM_records_provided_by_SN_as_zip_packages` merged. Mining was implemented using Spark pipe and run finishing successfully.

One thing we could think of is to unify the code for 'piping' because current job reuses code from tara reference extraction.
