### ISSUE TITLE
Carry out a quick research on sonar alternatives

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1278]
According to #1024 we cannot rely on sonar on different branches than the master one.

We could spend some time on finding viable alternatives. I've already came across:
* coveralls (test coverage)
* codacy (code quality)
* codeclimate (end-to-end visibility into continuous delivery, not that crucial in our small team)

All three are free for open source repos and can be easily integrated with github repositories.

We should make sure they would bring anything new to the table (like performing code analysis for pull requested branches etc).

We could take a quick look for other options as well.

**Comment by przemyslawjacewicz** [comment]
## **coveralls**
Great app but it's not an alternative to sonar because it only supports test coverage.

## **codacy**
This app seems to have all we need as sonar alternative
* it allows to scan different branches
* it allows to scan pull requests
* is free for open source projects

It's very user friendly - I've setup a scan of my IIS fork without looking into app docs. Scan results for pull requests are not visible in GitHub, they are visible in codacy app. It would be a bit better if the results were added as comments to PRs in GitHub, but the codacy app is very readable. Each issue can be drilled into the code to check the source of the issue. The default code pattern settings also seem to be quite loose. I've setup the integration with one of my public repos and I've had to enable all code pattern checks after adding `throw new RuntimeException()` to actually get a failed codacy check. 

Overall this is a very good application that gives probably everything we need within free plan for open source repositories.

## **codeclimate**
This app is broken into two parts - Velocity and Quality. The main product is Velocity which probably offers all the things we need but it is not free. Quality seems to be a subset of Velocity that offers code quality checks and is free. I've tested the integration with one of my public repos

* only one branch scanned by default
* pull requests are scanned 

The app detects other branches in source code but 'operates' only on one, default branch with other branch scans not available in the app ui. Pull requests are scanned and the app offers the ability to add comments to GitHub. But I couldn't get that working. I've used the same repo and the same pull request as before and could not get the app to find any issues and add some comments. The app offers the ability to change analysis settings but by default all code patterns are enabled and still nothing was found. So an explicit `throw new RuntimeException()` clause was not marked as bad code. In terms of user experience the app is not hard to configure but is less user friendly. 

Overall this is a good app but to get most of it we would probably need a paid plan.
