### ISSUE TITLE
Metadataextraction smoke test hangs

### ISSUE THREAD

**Issue by mpol** [openaire/iis#1349]
Recent runs, first after four years, hang and end in timeout even when the timeout is increased to 20h - the time before the hang is less than 1h anyway.
The last log line before the timeout is always `INFO MetadataExtractorMain: overriding default timeout: 600 with new value: 5 [secs]` 

The hang happened twice on the same document `2019-07-09_failures/e5501f998c6b4e30a7fa1e5c6006b6c8.pdf` on ci.ceon.pl: 
* https://ci.ceon.pl/view/IIS/job/metadataextraction_smoke_test/59/consoleFull
* https://ci.ceon.pl/view/IIS/job/metadataextraction_smoke_test/60/consoleFull

and twice on a different document `2018.07.23_failures/e451dfbbdce457f4d21c7385441cad80.pdf` on gorgona:
* https://gorgona.ocean.icm.edu.pl/job/openaire/job/metadataextraction_smoke_test/5/consoleFull
* https://gorgona.ocean.icm.edu.pl/job/openaire/job/metadataextraction_smoke_test/6/consoleFull

**Comment by marekhorst** [comment]
Long lasting execution might be bound to too little xmx memory assigned, [rerunning](http://ci.ceon.pl/view/IIS/job/metadataextraction_smoke_test/61/) with 6g. 

It might be the case the default value was altered (downgraded from `6g` to `4g`, to be aligned with current CERMINE cfg in IIS) but it wasn't tested on the PDFs sample. The last run was 4 years ago and the directory path name suggests those contents were added after the last execution.

md5 checksums of those contents are already blacklisted in the [IIS default config](https://git.icm.edu.pl/openaire/iis-deployment/-/blob/master/deploy/apps/primary/wf/primary/main/config-default/config-default.template):

`b0d1dcac85888095c5d912ce24cfdf35,136551da96fe8c11a13a4a275d19515b,92a56f29e66ec6bf9a47aa08b4b812c6,db20d96b3d79d87b0426c08cd99e6b85,b97413a3f73f087775901a2eded0e458,0055e6a649ef7c1235789a1bc0b7849b,efed713409fe01cc0e29e2dd707bae0d,138651fafa8bce896fe6971d9642329f,e451dfbbdce457f4d21c7385441cad80,e5501f998c6b4e30a7fa1e5c6006b6c8,2729e932176e661af4ba869bfe0064e0`

@mpol, I guess we should simply remove those two from the PDFs set or put them somewhere aside marking as requiring 6g of xmx (especially if [the test](http://ci.ceon.pl/view/IIS/job/metadataextraction_smoke_test/61/) I just triggered succeeds).

We prefer `4g` over `6g` because it gives better parallelization level in hadoop environment sacrificing just several PDFs which needs to be blacklisted.

**Comment by mpol** [comment]
> Long lasting execution might be bound to too little xmx memory assigned, [rerunning](http://ci.ceon.pl/view/IIS/job/metadataextraction_smoke_test/61/) with 6g.

http://ci.ceon.pl/view/IIS/job/metadataextraction_smoke_test/60/ was also run with 6g.

**Comment by mpol** [comment]
And anyway the timeout of 5s should work, no?

**Comment by marekhorst** [comment]
I have just moved the malicious PDFs from `/home/marek.horst/cermine/sanity_test/` to `/home/marek.horst/cermine/sanity_test_fatal_failures/` so they should be excluded from the smoke test. We could probably also move those contents from my home folder to some other location.

This is another execution without the two PDFs blocking CERMINE:
http://ci.ceon.pl/view/IIS/job/metadataextraction_smoke_test/62/
Let's see how it goes...

**Comment by marekhorst** [comment]
Jenkins build seems to be back to normal: http://ci.ceon.pl/job/metadataextraction_smoke_test/62/

**Comment by marekhorst** [comment]
Trying on gorgona now (also `6g` for now): https://gorgona.ocean.icm.edu.pl/job/openaire/job/metadataextraction_smoke_test/7/

**Comment by mpol** [comment]
It passed, but with 4g we get `java.lang.OutOfMemoryError: Java heap space` on 2729e932176e661af4ba869bfe0064e0.pdf: https://gorgona.ocean.icm.edu.pl/job/openaire/job/metadataextraction_smoke_test/8/consoleFull
