### ISSUE TITLE
List of tasks for cermine

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#337]

**Comment by marekhorst** [comment]
Here is my list, ordered by priority:

- https://github.com/CeON/CERMINE/issues/7 deal with long lasting executions by supporting timeout parameter or allowing thread interruption 
- improve US country code recognition in affiliations 
- [mantis#7803](https://mantis.vls.icm.edu.pl/view.php?id=7803) profile cermine due to increasing memory consumption - possible memory leak (reported on 2014-01-23, pretty old issue but important)
- [mantis#9095](https://mantis.vls.icm.edu.pl/view.php?id=9095) check bibliographic reference parser performance
- [mantis#7704](https://mantis.vls.icm.edu.pl/view.php?id=7704#c29105) scan through the most frequent failure causes - based on arxiv (reported on 2015-04-20). This is possibility of improving cermine resilience for problematic edge cases.

Please review: add/remove, change priority, comment.

**Comment by mkobos** [comment]
Here's my list ordered by priority with percentages roughly assessing the impact of each problem. The list is related to functionality of extracting affiliations. 

1. Affiliations: Improve way of finding country in affiliation string (this might potentially impact 23% of all records - these are the records where the country name (and thus country code) is missing)
    - 1.1 *Easy improvement*. Look for the name of the country in affiliation string (this might solve the problem in up to `23%*25%=` **6%** of all affiliation records).
    - 1.2 *More difficult improvement*. Recognize the country based on a dictionary of well-known scientific organizations and a dictionary of US states and major cities in various countries (this might solve the problem in up to `23%*80% =` **18%** of all affiliation records).
2. Affiliations: Improve recognizing whether given affiliation text is really an affiliation. This can be done using a simple rule that checks whether the text is not too short and not too long (this might impact up to **6%** of all affiliation records - these are the records where the affiliation text does not really correspond to an affiliation).
3. Affiliations: Improve mapping country name to country code. In huge majority of cases when the country code is missing while country name is not, the content of country name field contains a substring which is a name of a country. In these cases it should be possible to assign the correct country code. This problem appears in up to **1.6%** of all affiliation records (since this is the percentage of records where country code is missing while country name is not).
4. Affiliations: Recognize that some texts currently provided by CERMINE as affiliations are certainly not affiliations, e.g.: "Electronic address:" (this is the most numerous "affiliation" - it can be found in **0.03%** of all affiliation records), "These authors contributed equally to this work".
5. Affiliations: Improve cleaning the affiliation string because in a small number of cases, the organization field contains some text that doesn't belong there (e.g. address, short name, name of the organization in different language, unrelated text) This might impact up to **20%** of all affiliation records.

Note that all numbers come from the first version of report "Analysis of affiliations extracted by IIS from XMLs and PDFs" available at https://issue.openaire.research-infrastructures.eu/issues/2010, namely: https://issue.openaire.research-infrastructures.eu/attachments/download/509/2016-04-17_21_46_analysis.html. All these numbers are very rough approximations of the real values.

Note that point 1) in the list above addresses the problem "improve US country code recognition in affiliations" listed by @marekhorst  in https://github.com/openaire/iis/issues/337#issuecomment-212387162.

**Comment by marekhorst** [comment]
We've decided to start with @mkobos working on https://github.com/CeON/CERMINE/issues/7 and @dtkaczyk making some improvements on affiliation extraction.
