### ISSUE TITLE
Remove the dependence on snapshots

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#49]
IIS depends on snapshot version of certain modules. It's not only dangerous but also a big issue in case of mvn release.

**Comment by marekhorst** [comment]
This is expected since we have the following entry in `pom.xml` file:
```
<repository>
	<id>dnet4-snapshots</id>
	<name>D-Net 4 Snapshots</name>
	<url>http://maven.research-infrastructures.eu/nexus/content/repositories/dnet4-snapshots</url>
	<layout>default</layout>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
```
Unless there are non-dnet snapshot dependencies which is rather unlikely. I just checked one of the oozie `top` packages and I could find any other snapshot dependencies but dnet ones.

At "ancient svn times" we agreed to Alessia's idea on releasing plan (presented on one of the openaire meetings) and in particular to remove repositories providing snapshot dependencies from `pom.xml` when conducting activities related to releasing process. We were bringing them back after the release at the same time we updated IIS released versions to snapshots. 

The main advantage of this approach was obtaining most recent dnet patches and updates between (rather infrequent) releases while developing IIS modules. Now we can discuss whether we should/can be more strict in terms of dnet (but non-IIS) dependencies. We would need to judge whether the system is stable enough (or dnet releasing process easy enough) so we could stick to released dnet libs without blocking IIS development.

**Comment by lukdumi** [comment]
I am all for switching to the release versions, but OK, let's talk about it at our nearest meeting.

**Comment by marekhorst** [comment]
Oh, I just came across this issue again so let me update its status: in #150 I have switched dependencies from SNAPSHOTs to released versions for all DNet modules.

Currently the only SNAPSHOT jars appearing in oozie package are IIS libraries and CERMINE. The latter changes quite often (e.g. with crucial fixes) so we need to have latest possible version. Before release we would need to switch it to latest release.
